spring:
  profiles:
    active: local
  main:
    banner-mode: console
  application:
    name: "Lexware Coding Challenge"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5832/db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    hikari:
      schema: "lwcc"
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 100000
      connection-timeout: 30000
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: "lwcc"
    out-of-order: true
    baseline-on-migrate: true

server:
  servlet:
    context-path: "/api"

management:
  endpoint:
    health:
      probes:
        enabled: true

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /api-docs
