spring:
  profiles:
    active: local
  application:
    name: "Lexware Coding Challenge API Gateway"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: customer-service
            uri: http://localhost:8002
            predicates:
              - Path=/customers/**
            filters:
              - PrefixPath=/api
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
